# -*- coding: utf-8 -*-
"""IntenalassessmentLVADSUSR149.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGPyHY2moXD3XfYDA-XPwpQLsV8ZuPNP
"""

#1
length=float(input("enter the length in meters"))
width=float(input("enter the width in meters"))
Area=length*width
price ={'small':300,'medium':400,'large':500}
Category=input("enter the category as small ,medium or large")
if Category=='small':
  x= Area*price['small']
elif Category=="medium":
  x=Area*price['medium']
else :
  x=Area*price['large']

print(f"the pricing for ur land is {x}")

#2
weight=float(input("enter the weight"))
height=float(input("enter the height"))
Bmi= weight/(height*height)
if Bmi >16 and Bmi <23 :
  print("You have maintained ur body well.Having larger portions of protein helps u to maintain this")
elif Bmi > 24:
  print("Your bmi is little high than normal.Need to reduce ur portion of carbs and take fiber that helps u to be in balance")
else:
  print("Your bmi shows u r malnutritious,Take nutrients rich food and take fruits which are high in minerals")
print(Bmi)

#3
student_record={}
n=int(input("enter for how many students u want to record"))
for i in range(0,n):
  x=input("enter the student name")
  y=input("enter their grade")
  student_record[x]=y
option=int(input("enter the number 1,2 or 3 as add,update and retrieve "))
# adding another student

if(option==1):
  x1=input("enter the student_name")
  y1=input("enter their grade")
  student_record[x1]=y1
  print(student_record)
elif(option==2):
  key=input("enter the student name u want to update")
  value=input("enter their updated grade")
  student_record[key]=value
  print(student_record)
else:
  print(student_record)

#4
age=int(input("enter ur age"))
if(age<12):
  print("Below of age 12 we recommend u of movies of which of higher ratings in child section ")
elif(age>13 and age <=19):
  print("Above age 13 and below 20 we consider u as teens and given the movies based on  that")
elif(age>20 and age<30):
  print("above 20 and below 30 we consider u as a adult and movie recommendation based on that")
else:
  print("u r senior ppl and we recommend movie based on that")

#5
subscriber_id=[101,102,103,104,105,106,107]
even_subscriber=[]
for i in range(0,len(subscriber_id)):
  if (subscriber_id[i]%2==0):
    even_subscriber.append(subscriber_id[i])
print("These id were selected for promotional email campaign")
print(even_subscriber)

#6
password="deepi@123"
new_password=''
result=0
while result==0:
  new_password=input("enter the password then only we can let u in")
  if (new_password==password):
    print("Yay password correct !")
    result=1
  else:
    print("please retype ur password its wrong")
    result=0
    continue

#7
l=[]
customer=dict()
sum=0
for i in range(0,3):
  x=input("enter the id")
  y=int(input("enter the ratings"))
  sum+=y
  l.append(y)
  customer[x]=y
avg=sum/len(customer)
for i in l:
  print(f' person no1,2,3')
  if(i<avg):
    print("customer feedback is not good need to improve")
  elif(i==avg):
    print("not bad somehow solved the customer issues but not fully")
  else:
    print("Good job, u have did a good job")

#8
comments=input("enter ur comments")
count=0
for i in comments:
  if (i =='a' or i=='e' or i=='i' or i=='o' or i=='u'):
    count=count+1
if (count<len(comments)/2):
  print("Low effort comments")
elif(count>len(comments)/2):
  print("high effort comments")
else:
  print("spammmy comments")

#9
import datetime
time =input("enter the time in the format of %H %M")
event_time='11:00'
if (event_time!=time):
  print(f"Ur event is not yet started {event_time} please start soon")
else:
  print(f"ur event is started please make sure u attend that ")

#10

#11
try:
  polling_system=str(input("enter the party u want to vote bjp,modi"))
  if (polling_system=='bjp' or polling_system=='modi'):
    print("THAKS FOR MAKING A VOTE")
except  NameError:
  print("This party is not included pls vote correctly")

#12
a=int(input('enter the value'))
b=4
try:
  if (b/a)==1:
    print("odd")
except:
  print("error occured")

#13
log_time='10:00'
if (log_time=='10:00'):
  var=("/content/untitled",'r')
  var.read()
  var=("login reports monday 10 am to 6pm completed todays task",'w')
  var.write()
  var.close()

#14
log_files_time='10:00'
if (log_files_time=='10:00'):
  # for reviewing the system logs
  var=("/content/untitled",'r')
  var.read()
  # for writing ur reports on that
  var=("login reports monday 10 am to 6pm completed todays task",'w')
  var.write()
  var.close()

#15