# -*- coding: utf-8 -*-
"""LVADSUSR149__FINAL_ASSESSMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yt1pSryY1Bh427C9DI99CbpbxoI2RKW4
"""

#1
import pandas as pd
p=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})
p.iloc[1,1]

#1a
#Load data set using pandas
import pandas as pd
df=pd.read_csv('/content/sample_data/Final Dataset - IPL.csv')
df

#1b
#rows and columns
df.shape
# Analysing the data
df.describe()
#checking null value
df.isnull()
#if its null
df.fillna(0)

#2a
check=df.isnull()==True
print(check)

#There is no null or missing value in the dataset.I identified that with the help of isnull() function.

#Replace: If in some condition there is any null value i would use isnull() to check and if its true, I would use fillna() function to replace that with values.

#Drop: I dont think drop is a suitable option here. We can't drop something like this.It could affect the data.

#2b
#There is no duplicate elements

#3a
df
# describe is used to analyse the measures like mean,median,standard deviation
# varianceand their tendencies
df.describe()
mean=df[['match_id','first_ings_score',	'first_ings_wkts',	'second_ings_score','second_ings_wkts',	'margin',	'highscore']].mean()
print(mean)

mode=mode=df[['match_id','first_ings_score',	'first_ings_wkts',	'second_ings_score','second_ings_wkts',	'margin',	'highscore']].mode()
print(mode)

median=df[['match_id','first_ings_score',	'first_ings_wkts',	'second_ings_score','second_ings_wkts',	'margin',	'highscore']].median()
print(median)

std=df[['match_id','first_ings_score',	'first_ings_wkts',	'second_ings_score','second_ings_wkts',	'margin',	'highscore']].std()
print(std)

variance=df[['match_id','first_ings_score',	'first_ings_wkts',	'second_ings_score','second_ings_wkts',	'margin',	'highscore']].var()
print(variance)

#4a
# bar plot
import matplotlib.pyplot as plt
min=df.groupby('toss_decision').agg({'first_ings_score':'sum'}).reset_index()
plt.bar(min['toss_decision'],min['first_ings_score'])
plt.show()

#4a line chart
min=df.groupby('toss_decision').agg({'first_ings_score':'sum','second_ings_score':'sum'}).reset_index()
#plt.bar(min['toss_decision'],min['first_ings_score'])
min.plot(x='toss_decision',y=['first_ings_score','second_ings_score'],kind='line')
plt.xlabel('Toss decisions')
plt.ylabel('Innings on first and second')
plt.title("Innings based upon Toss Decision")
plt.show()

#4a
#pie chart
df['stage'].value_counts().plot.pie(autopct = '%1.f%%')

#5a

import matplotlib.pyplot as plt
min=df.groupby('toss_decision').agg({'first_ings_score':'sum','second_ings_score':'sum'}).reset_index()
#plt.bar(min['toss_decision'],min['first_ings_score'])
min.plot(x='toss_decision',y=['first_ings_score','second_ings_score'],kind='bar')
plt.show()

#6a

#7a
#hist-distribution
month=df.groupby('team1').agg({'first_ings_score':'sum'})
plt.xlabel('Team')
plt.ylabel('Innings Score')
plt.hist(month.values,bins=5)
plt.show()

#8
min=df[df['highscore']> 90].head(5)
# df.plot(x='top_scorer',kind='bar')
# plt.plot(df['top_scorer'],df['best_bowling'])
# plt.show()
#min.plot(x='highscore',y='won_by')
plt.plot(min['highscore'],min['won_by'])

"""9)

**From 4a bar chart**- I can see there are team who winned in the toss has taken a field and got a higher score compared to people who are in batting.

It clearly shows in the first innings score field teams got higher score so there would be above 60% of possibility that team who are assigned in field  could be a winner.

**From 4a:**
From pie chart I want to know how many matches were conducted based on different stages.
Insights:


*   95% of matches were in the stage of group
*   4%  of matches in playoff


*   Remaining % in Final
From this we get to know the more matches were happened as group matches.Very less matches for playoff

**From 6,7,8**

__Team Based inning score are also we can analyse using these charts
High performer who won by highest score can also be able to identify from the charts.

* Based on that information, we can identify who are all the top performers and best bowlers on their team success.





"""